services:
  - type: web
    name: bloodonal-api
    runtime: python3.12
    env: python
    region: frankfurt
    plan: free

    buildCommand: |
      python -m pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    autoDeploy: true

    envVars:
      - key: ENVIRONMENT
        value: "production"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: DEBUG
        value: "false"
      # Do not add SECRET_KEY or DB password here in the file â€” set them in Render UI

    # Optionally mount the firebase secret file if you prefer that approach:
    secrets:
      - name: firebase.json
        mountPath: /etc/secrets/firebase.json
