apiVersion: v1
kind: Service
metadata:
  name: bloodonal-fastapi-service
spec:
  selector:
    app: bloodonal-fastapi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080  # Port your FastAPI app listens on
  type: LoadBalancer  # Use ClusterIP for internal-only access
